### PR TITLE
SSJ Scenario: Verifying applicant does not see Your Applications tab …

### PR DESCRIPTION
**Pull request by iamdez99**
…if applicant has not applied to a Vacancy

### CODE REVIEW

**Review by iamdez99 — COMMENTED** [review]
Reviewed

**Review by hamidnesar — APPROVED** [review]
Reviewed and Approved!

**Review by sarwarahmed1 — APPROVED** [review]

**Review by matakevin — APPROVED** [review]
LGTM

**Review by Mariachaudhry — APPROVED** [review]

**Review by puzikovam2 — APPROVED** [review]
approved by @puzikovam2

**Pull request merged**
