### PR TITLE
EM Automation ENTMAINT-943

### PR DESCRIPTION
**Pull request by iamdez99**

### CODE REVIEW

**Review by puzikovam2 — APPROVED** [review]
approved by @puzikovam2

**Comment by alenaminsk** [comment]
👍

**Review by andreyeve — APPROVED** [review]
Just fix the progression tag and you are good to go!

**Review by georgeb79 — APPROVED** [review]

**Review by sarwarahmed1 — APPROVED** [review]

**Review by spkoirala — APPROVED** [review]
Looks good to me.

**Pull request merged**
